<?php
/**
 * This class has been auto-generated by PHP-DI.
 */
class CompiledContainer extends DI\CompiledContainer{
    const METHOD_MAPPING = array (
  'Craftsman\\Contracts\\IBlock' => 'get5d3478db17025030546763',
);

    protected function get5d3478db17025030546763()
    {
        $object = new Craftsman\Blocks\Greeting();
        return $object;
    }

}
